import type { Metadata } from "next";
import "./globals.css";
import { CartContextProvider } from "@/providers/CartContext/CartContext";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartContextProvider>
        <body className="">
          <Toaster position="top-right" />
          <Navbar />
          {children}
        </body>
      </CartContextProvider>
    </html>
  );
}
